name: Hello

on: 
  workflow_dispatch


jobs:
    terraform:
      runs-on: ubuntu-latest
      environment:  aws

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS Credentials
        run: |
           echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
           echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
           echo "AWS_SECRET_KEY${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV
           export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
           export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
           export AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: 1.9.5

      - name: Init Terraform 
        run: terraform init

      - name: Terraform plan
        run: terraform plan 

      - name: Terraform apply
        run: terraform apply
